
services:
  gollm-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gollm-development
    volumes:
      - .:/workspace
      - gollm-cache:/workspace/.gollm/cache
    working_dir: /workspace
    environment:
      - PYTHONPATH=/workspace/src
      - goLLM_CONFIG=/workspace/gollm.json
    command: tail -f /dev/null
    
  gollm-test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gollm-testing
    volumes:
      - .:/workspace
    working_dir: /workspace
    environment:
      - PYTHONPATH=/workspace/src
    command: pytest tests/ -v --cov=src/gollm

volumes:
  gollm-cache:
